# image base from docker-hub
FROM openjdk:8-jdk-alpine

# Volume location
VOLUME /tmp

# port image target
EXPOSE 8181

# add or copy file from target folder
ADD target/springbootapp-0.1.jar springbootapp-0.1.jar

# syntax for run application.properties file
ENTRYPOINT ["java","-jar","/springbootapp-0.1.jar"]