# Create image based on the official Node 6 image from dockerhub 
FROM node:7.6 

# Create a directory where our app will be placed 
RUN mkdir -p /usr/src/app 

# Change directory so that our commands run inside this new directory 
WORKDIR /usr/src/app 

# Copy dependency definitions 
COPY package.json /usr/src/app 

# Get all the code needed to run the app 
COPY . /usr/src/app 

#install angular-cli 
RUN npm install -g @angular/cli@^1.0.0-rc.2 

# Install dependecies 
RUN npm install 

#add @types lodash 
RUN npm install  @types/lodash@4.14.50 

#clear npm cache 
RUN npm cache clear 

# Expose the port the app runs in 
EXPOSE 4200 

# Serve the app 
CMD ["ng", "serve", "--prod", "--aot","--host", "0.0.0.0"]